#############################################################################
# Makefile for building: 5640_linux_qt
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  5640_linux_qt.pro
# Template: app
# Command: /mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/bin/qmake -o Makefile 5640_linux_qt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -I/include -DZYNQ -march=armv7-a -mtune=cortex-a9 -mcpu=cortex-a9 -mfpu=neon -pipe -fomit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-psabi -I/include -DZYNQ -pipe -I/include -DZYNQ -march=armv7-a -mtune=cortex-a9 -mcpu=cortex-a9 -mfpu=neon -pipe -fomit-frame-pointer -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../depends/opencv/opencv/include -I../../../../depends/ncnn/ncnn/include -I../../../../qt5-lab/images/qt5-arm-5.11.2/include -I../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets -I../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui -I../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore -I. -I. -I../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/devices/linux-arm-xilinx-zynq-g++
QMAKE         = /mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 5640_linux_qt1.0.0
DISTDIR = /mnt/workspace/driver_app/app_code/CH09_5640_qt/5640_qt/.tmp/5640_linux_qt1.0.0
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -L/lib -Wl,-O1 -Wl,-rpath,/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/lib
LIBS          = $(SUBLIBS) -L/mnt/workspace/depends/opencv/opencv/lib/ -lopencv_imgcodecs -lopencv_imgproc -lopencv_core -lopencv_highgui -L/mnt/workspace/depends/opencv/opencv/share/OpenCV/3rdparty/lib/ -lzlib -llibjasper -llibjpeg -fopenmp -L/mnt/workspace/depends/ncnn/ncnn/lib/ -lncnn -L/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/lib -lQt5Widgets -lQt5Gui -lQt5Core -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mtcnn.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mtcnn.o \
		moc_mainwindow.o
DIST          = ../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/spec_pre.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/unix.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/linux.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/sanitize.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/gcc-base.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/gcc-base-unix.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/g++-base.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/g++-unix.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/qdevice.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/device_config.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/qconfig.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_core.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_core_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_dbus.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_gui.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_network.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_network_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_sql.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_testlib.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_widgets.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_xml.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt_functions.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt_config.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/exclusive_builds.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/toolchain.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/default_pre.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/resolve_config.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/default_post.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/warn_on.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/resources.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/moc.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/uic.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/unix/thread.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qmake_use.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/file_copies.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/testcase_targets.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/exceptions.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/yacc.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/lex.prf \
		5640_linux_qt.pro mainwindow.h main.cpp \
		mainwindow.cpp \
		mtcnn.cpp
QMAKE_TARGET  = 5640_linux_qt
DESTDIR       = 
TARGET        = 5640_linux_qt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 5640_linux_qt.pro ../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf ../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/spec_pre.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/unix.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/linux.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/sanitize.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/gcc-base.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/gcc-base-unix.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/g++-base.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/g++-unix.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/qdevice.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/device_config.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/qconfig.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_core.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_core_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_dbus.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_gui.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_network.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_network_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_sql.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_testlib.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_widgets.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_xml.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_zlib_private.pri \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt_functions.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt_config.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/exclusive_builds.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/toolchain.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/default_pre.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/resolve_config.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/default_post.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/warn_on.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/resources.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/moc.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/uic.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/unix/thread.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qmake_use.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/file_copies.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/testcase_targets.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/exceptions.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/yacc.prf \
		../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/lex.prf \
		5640_linux_qt.pro \
		../../../../qt5-lab/images/qt5-arm-5.11.2/lib/libQt5Widgets.prl \
		../../../../qt5-lab/images/qt5-arm-5.11.2/lib/libQt5Gui.prl \
		../../../../qt5-lab/images/qt5-arm-5.11.2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile 5640_linux_qt.pro
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/spec_pre.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/unix.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/linux.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/sanitize.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/gcc-base.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/gcc-base-unix.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/g++-base.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/common/g++-unix.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/qdevice.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/device_config.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/qconfig.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_concurrent.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_core.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_core_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_dbus.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_gui.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_gui_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_network.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_network_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_printsupport.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_sql.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_sql_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_testlib.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_widgets.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_xml.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_xml_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/modules/qt_lib_zlib_private.pri:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt_functions.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt_config.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/devices/linux-arm-xilinx-zynq-g++/qmake.conf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/exclusive_builds.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/toolchain.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/default_pre.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/resolve_config.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/default_post.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/warn_on.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qt.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/resources.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/moc.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/uic.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/unix/thread.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/qmake_use.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/file_copies.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/testcase_targets.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/exceptions.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/yacc.prf:
../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/lex.prf:
5640_linux_qt.pro:
../../../../qt5-lab/images/qt5-arm-5.11.2/lib/libQt5Widgets.prl:
../../../../qt5-lab/images/qt5-arm-5.11.2/lib/libQt5Gui.prl:
../../../../qt5-lab/images/qt5-arm-5.11.2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 5640_linux_qt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mtcnn.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/data/dummy.cpp
	arm-linux-gnueabihf-g++ -pipe -Wno-psabi -I/include -DZYNQ -pipe -I/include -DZYNQ -march=armv7-a -mtune=cortex-a9 -mcpu=cortex-a9 -mfpu=neon -pipe -fomit-frame-pointer -O2 -Wall -W -dM -E -o moc_predefs.h ../../../../qt5-lab/images/qt5-arm-5.11.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QMainWindow \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qmainwindow.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtwidgetsglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtguiglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qconfig-bootstrapped.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qconfig.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtcore-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsystemdetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qprocessordetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcompilerdetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtypeinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsysinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlogging.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qflags.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbasicatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_bootstrap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qgenericatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_cxx11.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_msvc.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qglobalstatic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmutex.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qnumeric.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qversiontagging.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtgui-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtwidgets-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qwindowdefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobjectdefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qnamespace.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobjectdefs_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qwindowdefs_win.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobject.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstring.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qchar.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbytearray.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qrefcount.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qarraydata.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringliteral.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringalgorithms.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringview.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringbuilder.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qalgorithms.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qiterator.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qhashfunctions.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qpair.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbytearraylist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringlist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qregexp.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringmatcher.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcoreevent.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qscopedpointer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmetatype.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvarlengtharray.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcontainerfwd.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobject_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmargins.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpaintdevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qrect.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsize.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qpoint.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpalette.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qcolor.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qrgb.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qrgba64.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qbrush.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvector.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qmatrix.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpolygon.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qregion.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdatastream.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qiodevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qline.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtransform.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpainterpath.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qimage.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpixelformat.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpixmap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsharedpointer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qshareddata.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qhash.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsharedpointer_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfont.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfontmetrics.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfontinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qsizepolicy.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qcursor.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qkeysequence.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qevent.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvariant.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdebug.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtextstream.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlocale.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qset.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcontiguouscache.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qurl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qurlquery.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfile.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfiledevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qvector2d.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtouchdevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtabwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qicon.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QFileDialog \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qfiledialog.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdir.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfileinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qdialog.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/QPixmap \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/QImage \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QLabel \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qlabel.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qframe.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/QTimer \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtimer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbasictimer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/QThread \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qthread.h \
		../../../../depends/opencv/opencv/include/opencv2/opencv.hpp \
		../../../../depends/opencv/opencv/include/opencv2/opencv_modules.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvdef.h \
		../../../../depends/opencv/opencv/include/opencv2/core/hal/interface.h \
		../../../../depends/opencv/opencv/include/opencv2/core/cv_cpu_dispatch.h \
		../../../../depends/opencv/opencv/include/opencv2/core/cv_cpu_helper.h \
		../../../../depends/opencv/opencv/include/opencv2/core/version.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/base.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvstd.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/ptr.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/neon_utils.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/vsx_utils.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/traits.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/matx.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/saturate.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/fast_math.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/types.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/mat.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/bufferpool.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/mat.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/persistence.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/operations.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvstd.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/utility.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/core_c.h \
		../../../../depends/opencv/opencv/include/opencv2/core/types_c.h \
		../../../../depends/opencv/opencv/include/opencv2/core/optim.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/ovx.hpp \
		../../../../depends/opencv/opencv/include/opencv2/calib3d.hpp \
		../../../../depends/opencv/opencv/include/opencv2/features2d.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/miniflann.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/defines.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/config.h \
		../../../../depends/opencv/opencv/include/opencv2/core/affine.hpp \
		../../../../depends/opencv/opencv/include/opencv2/calib3d/calib3d_c.h \
		../../../../depends/opencv/opencv/include/opencv2/flann.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/flann_base.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/general.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/matrix.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/params.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/any.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/saving.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/nn_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/result_set.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/all_indices.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kdtree_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/dynamic_bitset.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/dist.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/heap.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/allocator.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/random.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kdtree_single_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kmeans_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/logger.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/composite_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/linear_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/lsh_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/lsh_table.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/autotuned_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/ground_truth.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/index_testing.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/timer.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/sampling.h \
		../../../../depends/opencv/opencv/include/opencv2/highgui.hpp \
		../../../../depends/opencv/opencv/include/opencv2/imgcodecs.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videoio.hpp \
		../../../../depends/opencv/opencv/include/opencv2/highgui/highgui_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc/imgproc_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc/types_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../../depends/opencv/opencv/include/opencv2/videoio/videoio_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc.hpp \
		../../../../depends/opencv/opencv/include/opencv2/ml.hpp \
		../../../../depends/opencv/opencv/include/opencv2/ml/ml.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect/objdetect_c.h \
		../../../../depends/opencv/opencv/include/opencv2/photo.hpp \
		../../../../depends/opencv/opencv/include/opencv2/photo/photo_c.h \
		../../../../depends/opencv/opencv/include/opencv2/shape.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/emdL1.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/shape_transformer.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/hist_cost.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/shape_distance.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/warpers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/warpers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda_types.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/matchers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/util.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/util_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/camera.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/blenders.hpp \
		../../../../depends/opencv/opencv/include/opencv2/superres.hpp \
		../../../../depends/opencv/opencv/include/opencv2/superres/optical_flow.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/tracking.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/background_segm.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/tracking_c.h \
		../../../../depends/opencv/opencv/include/opencv2/videostab.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/stabilizer.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/global_motion.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/optical_flow.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/motion_core.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/outlier_rejection.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/frame_source.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/log.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/inpainting.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/fast_marching.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/deblurring.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/wobble_suppression.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/ring_buffer.hpp \
		mtcnn.h \
		../../../../depends/ncnn/ncnn/include/net.h \
		../../../../depends/ncnn/ncnn/include/blob.h \
		../../../../depends/ncnn/ncnn/include/platform.h \
		../../../../depends/ncnn/ncnn/include/layer.h \
		../../../../depends/ncnn/ncnn/include/mat.h \
		../../../../depends/ncnn/ncnn/include/modelbin.h \
		../../../../depends/ncnn/ncnn/include/paramdict.h \
		mainwindow.h \
		moc_predefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/bin/moc
	/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/bin/moc $(DEFINES) --include /mnt/workspace/driver_app/app_code/CH09_5640_qt/5640_qt/moc_predefs.h -I/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/mkspecs/devices/linux-arm-xilinx-zynq-g++ -I/mnt/workspace/driver_app/app_code/CH09_5640_qt/5640_qt -I/mnt/workspace/depends/opencv/opencv/include -I/mnt/workspace/depends/ncnn/ncnn/include -I/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/include -I/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets -I/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/include/QtGui -I/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/include/QtCore -I/mnt/workspace/qt5-lab/tools/cross_compiler/arm-linux-gnueabihf/include/c++/6.2.1 -I/mnt/workspace/qt5-lab/tools/cross_compiler/arm-linux-gnueabihf/include/c++/6.2.1/arm-linux-gnueabihf -I/mnt/workspace/qt5-lab/tools/cross_compiler/arm-linux-gnueabihf/include/c++/6.2.1/backward -I/mnt/workspace/qt5-lab/tools/cross_compiler/lib/gcc/arm-linux-gnueabihf/6.2.1/include -I/mnt/workspace/qt5-lab/tools/cross_compiler/lib/gcc/arm-linux-gnueabihf/6.2.1/include-fixed -I/mnt/workspace/qt5-lab/tools/cross_compiler/arm-linux-gnueabihf/include -I/mnt/workspace/qt5-lab/tools/cross_compiler/arm-linux-gnueabihf/libc/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../../qt5-lab/images/qt5-arm-5.11.2/bin/uic
	/mnt/workspace/qt5-lab/images/qt5-arm-5.11.2/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QMainWindow \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qmainwindow.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtwidgetsglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtguiglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qconfig-bootstrapped.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qconfig.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtcore-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsystemdetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qprocessordetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcompilerdetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtypeinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsysinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlogging.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qflags.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbasicatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_bootstrap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qgenericatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_cxx11.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_msvc.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qglobalstatic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmutex.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qnumeric.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qversiontagging.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtgui-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtwidgets-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qwindowdefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobjectdefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qnamespace.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobjectdefs_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qwindowdefs_win.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobject.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstring.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qchar.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbytearray.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qrefcount.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qarraydata.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringliteral.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringalgorithms.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringview.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringbuilder.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qalgorithms.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qiterator.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qhashfunctions.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qpair.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbytearraylist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringlist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qregexp.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringmatcher.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcoreevent.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qscopedpointer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmetatype.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvarlengtharray.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcontainerfwd.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobject_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmargins.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpaintdevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qrect.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsize.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qpoint.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpalette.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qcolor.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qrgb.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qrgba64.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qbrush.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvector.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qmatrix.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpolygon.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qregion.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdatastream.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qiodevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qline.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtransform.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpainterpath.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qimage.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpixelformat.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpixmap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsharedpointer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qshareddata.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qhash.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsharedpointer_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfont.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfontmetrics.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfontinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qsizepolicy.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qcursor.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qkeysequence.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qevent.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvariant.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdebug.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtextstream.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlocale.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qset.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcontiguouscache.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qurl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qurlquery.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfile.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfiledevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qvector2d.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtouchdevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtabwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qicon.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QFileDialog \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qfiledialog.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdir.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfileinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qdialog.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/QPixmap \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/QImage \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QLabel \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qlabel.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qframe.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/QTimer \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtimer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbasictimer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/QThread \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qthread.h \
		../../../../depends/opencv/opencv/include/opencv2/opencv.hpp \
		../../../../depends/opencv/opencv/include/opencv2/opencv_modules.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvdef.h \
		../../../../depends/opencv/opencv/include/opencv2/core/hal/interface.h \
		../../../../depends/opencv/opencv/include/opencv2/core/cv_cpu_dispatch.h \
		../../../../depends/opencv/opencv/include/opencv2/core/cv_cpu_helper.h \
		../../../../depends/opencv/opencv/include/opencv2/core/version.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/base.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvstd.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/ptr.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/neon_utils.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/vsx_utils.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/traits.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/matx.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/saturate.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/fast_math.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/types.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/mat.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/bufferpool.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/mat.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/persistence.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/operations.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvstd.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/utility.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/core_c.h \
		../../../../depends/opencv/opencv/include/opencv2/core/types_c.h \
		../../../../depends/opencv/opencv/include/opencv2/core/optim.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/ovx.hpp \
		../../../../depends/opencv/opencv/include/opencv2/calib3d.hpp \
		../../../../depends/opencv/opencv/include/opencv2/features2d.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/miniflann.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/defines.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/config.h \
		../../../../depends/opencv/opencv/include/opencv2/core/affine.hpp \
		../../../../depends/opencv/opencv/include/opencv2/calib3d/calib3d_c.h \
		../../../../depends/opencv/opencv/include/opencv2/flann.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/flann_base.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/general.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/matrix.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/params.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/any.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/saving.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/nn_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/result_set.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/all_indices.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kdtree_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/dynamic_bitset.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/dist.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/heap.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/allocator.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/random.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kdtree_single_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kmeans_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/logger.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/composite_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/linear_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/lsh_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/lsh_table.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/autotuned_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/ground_truth.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/index_testing.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/timer.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/sampling.h \
		../../../../depends/opencv/opencv/include/opencv2/highgui.hpp \
		../../../../depends/opencv/opencv/include/opencv2/imgcodecs.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videoio.hpp \
		../../../../depends/opencv/opencv/include/opencv2/highgui/highgui_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc/imgproc_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc/types_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../../depends/opencv/opencv/include/opencv2/videoio/videoio_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc.hpp \
		../../../../depends/opencv/opencv/include/opencv2/ml.hpp \
		../../../../depends/opencv/opencv/include/opencv2/ml/ml.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect/objdetect_c.h \
		../../../../depends/opencv/opencv/include/opencv2/photo.hpp \
		../../../../depends/opencv/opencv/include/opencv2/photo/photo_c.h \
		../../../../depends/opencv/opencv/include/opencv2/shape.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/emdL1.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/shape_transformer.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/hist_cost.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/shape_distance.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/warpers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/warpers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda_types.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/matchers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/util.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/util_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/camera.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/blenders.hpp \
		../../../../depends/opencv/opencv/include/opencv2/superres.hpp \
		../../../../depends/opencv/opencv/include/opencv2/superres/optical_flow.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/tracking.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/background_segm.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/tracking_c.h \
		../../../../depends/opencv/opencv/include/opencv2/videostab.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/stabilizer.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/global_motion.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/optical_flow.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/motion_core.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/outlier_rejection.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/frame_source.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/log.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/inpainting.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/fast_marching.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/deblurring.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/wobble_suppression.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/ring_buffer.hpp \
		mtcnn.h \
		../../../../depends/ncnn/ncnn/include/net.h \
		../../../../depends/ncnn/ncnn/include/blob.h \
		../../../../depends/ncnn/ncnn/include/platform.h \
		../../../../depends/ncnn/ncnn/include/layer.h \
		../../../../depends/ncnn/ncnn/include/mat.h \
		../../../../depends/ncnn/ncnn/include/modelbin.h \
		../../../../depends/ncnn/ncnn/include/paramdict.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QApplication \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qapplication.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcoreapplication.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qeventloop.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qdesktopwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qguiapplication.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QMainWindow \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qmainwindow.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtwidgetsglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtguiglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qglobal.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qconfig-bootstrapped.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qconfig.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtcore-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsystemdetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qprocessordetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcompilerdetection.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtypeinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsysinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlogging.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qflags.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbasicatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_bootstrap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qgenericatomic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_cxx11.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qatomic_msvc.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qglobalstatic.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmutex.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qnumeric.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qversiontagging.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtgui-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtwidgets-config.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qwindowdefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobjectdefs.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qnamespace.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobjectdefs_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qwindowdefs_win.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobject.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstring.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qchar.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbytearray.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qrefcount.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qarraydata.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringliteral.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringalgorithms.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringview.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringbuilder.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qalgorithms.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qiterator.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qhashfunctions.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qpair.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbytearraylist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringlist.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qregexp.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qstringmatcher.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcoreevent.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qscopedpointer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmetatype.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvarlengtharray.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcontainerfwd.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qobject_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmargins.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpaintdevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qrect.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsize.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qpoint.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpalette.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qcolor.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qrgb.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qrgba64.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qbrush.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvector.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qmatrix.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpolygon.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qregion.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdatastream.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qiodevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qline.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtransform.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpainterpath.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qimage.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpixelformat.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qpixmap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsharedpointer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qshareddata.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qhash.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qsharedpointer_impl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfont.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfontmetrics.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qfontinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qsizepolicy.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qcursor.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qkeysequence.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qevent.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qvariant.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qmap.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdebug.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtextstream.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qlocale.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qset.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qcontiguouscache.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qurl.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qurlquery.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfile.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfiledevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qvector2d.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qtouchdevice.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qtabwidget.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/qicon.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QFileDialog \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qfiledialog.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qdir.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qfileinfo.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qdialog.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/QPixmap \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtGui/QImage \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/QLabel \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qlabel.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtWidgets/qframe.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/QTimer \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qtimer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qbasictimer.h \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/QThread \
		../../../../qt5-lab/images/qt5-arm-5.11.2/include/QtCore/qthread.h \
		../../../../depends/opencv/opencv/include/opencv2/opencv.hpp \
		../../../../depends/opencv/opencv/include/opencv2/opencv_modules.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvdef.h \
		../../../../depends/opencv/opencv/include/opencv2/core/hal/interface.h \
		../../../../depends/opencv/opencv/include/opencv2/core/cv_cpu_dispatch.h \
		../../../../depends/opencv/opencv/include/opencv2/core/cv_cpu_helper.h \
		../../../../depends/opencv/opencv/include/opencv2/core/version.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/base.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvstd.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/ptr.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/neon_utils.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/vsx_utils.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/traits.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/matx.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/saturate.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/fast_math.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/types.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/mat.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/bufferpool.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/mat.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/persistence.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/operations.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cvstd.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/utility.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/core_c.h \
		../../../../depends/opencv/opencv/include/opencv2/core/types_c.h \
		../../../../depends/opencv/opencv/include/opencv2/core/optim.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/ovx.hpp \
		../../../../depends/opencv/opencv/include/opencv2/calib3d.hpp \
		../../../../depends/opencv/opencv/include/opencv2/features2d.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/miniflann.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/defines.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/config.h \
		../../../../depends/opencv/opencv/include/opencv2/core/affine.hpp \
		../../../../depends/opencv/opencv/include/opencv2/calib3d/calib3d_c.h \
		../../../../depends/opencv/opencv/include/opencv2/flann.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/flann_base.hpp \
		../../../../depends/opencv/opencv/include/opencv2/flann/general.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/matrix.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/params.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/any.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/saving.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/nn_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/result_set.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/all_indices.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kdtree_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/dynamic_bitset.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/dist.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/heap.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/allocator.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/random.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kdtree_single_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/kmeans_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/logger.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/composite_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/linear_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/hierarchical_clustering_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/lsh_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/lsh_table.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/autotuned_index.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/ground_truth.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/index_testing.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/timer.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/sampling.h \
		../../../../depends/opencv/opencv/include/opencv2/highgui.hpp \
		../../../../depends/opencv/opencv/include/opencv2/imgcodecs.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videoio.hpp \
		../../../../depends/opencv/opencv/include/opencv2/highgui/highgui_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc/imgproc_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc/types_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgcodecs/imgcodecs_c.h \
		../../../../depends/opencv/opencv/include/opencv2/videoio/videoio_c.h \
		../../../../depends/opencv/opencv/include/opencv2/imgproc.hpp \
		../../../../depends/opencv/opencv/include/opencv2/ml.hpp \
		../../../../depends/opencv/opencv/include/opencv2/ml/ml.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect/detection_based_tracker.hpp \
		../../../../depends/opencv/opencv/include/opencv2/objdetect/objdetect_c.h \
		../../../../depends/opencv/opencv/include/opencv2/photo.hpp \
		../../../../depends/opencv/opencv/include/opencv2/photo/photo_c.h \
		../../../../depends/opencv/opencv/include/opencv2/shape.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/emdL1.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/shape_transformer.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/hist_cost.hpp \
		../../../../depends/opencv/opencv/include/opencv2/shape/shape_distance.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/warpers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/warpers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda_types.hpp \
		../../../../depends/opencv/opencv/include/opencv2/core/cuda.inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/warpers_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/matchers.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/motion_estimators.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/util.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/util_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/camera.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/exposure_compensate.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/seam_finders.hpp \
		../../../../depends/opencv/opencv/include/opencv2/stitching/detail/blenders.hpp \
		../../../../depends/opencv/opencv/include/opencv2/superres.hpp \
		../../../../depends/opencv/opencv/include/opencv2/superres/optical_flow.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/tracking.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/background_segm.hpp \
		../../../../depends/opencv/opencv/include/opencv2/video/tracking_c.h \
		../../../../depends/opencv/opencv/include/opencv2/videostab.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/stabilizer.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/global_motion.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/optical_flow.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/motion_core.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/outlier_rejection.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/motion_stabilizing.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/frame_source.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/log.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/inpainting.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/fast_marching.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/fast_marching_inl.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/deblurring.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/wobble_suppression.hpp \
		../../../../depends/opencv/opencv/include/opencv2/videostab/ring_buffer.hpp \
		mtcnn.h \
		../../../../depends/ncnn/ncnn/include/net.h \
		../../../../depends/ncnn/ncnn/include/blob.h \
		../../../../depends/ncnn/ncnn/include/platform.h \
		../../../../depends/ncnn/ncnn/include/layer.h \
		../../../../depends/ncnn/ncnn/include/mat.h \
		../../../../depends/ncnn/ncnn/include/modelbin.h \
		../../../../depends/ncnn/ncnn/include/paramdict.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mtcnn.o: mtcnn.cpp mtcnn.h \
		../../../../depends/ncnn/ncnn/include/net.h \
		../../../../depends/ncnn/ncnn/include/blob.h \
		../../../../depends/ncnn/ncnn/include/platform.h \
		../../../../depends/ncnn/ncnn/include/layer.h \
		../../../../depends/ncnn/ncnn/include/mat.h \
		../../../../depends/opencv/opencv/include/opencv2/flann/allocator.h \
		../../../../depends/ncnn/ncnn/include/modelbin.h \
		../../../../depends/ncnn/ncnn/include/paramdict.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mtcnn.o mtcnn.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

